// Combine all routes
import { Router } from "express";
import addressRoutes from "../modules/address/address.routes";
import authRouter from "../modules/auth/auth.routes";
import cartRoute from "../modules/cart/cart.routes";
import categoriesRoutes from "../modules/category/category.routes";
import childCategoriesRoutes from "../modules/childCategory/childCategory.routes";
import couponRoute from "../modules/coupon/coupon.routes";
import emailTemplateRoutes from "../modules/emailTemplate/emailTemplate.routes";
import offersRoute from "../modules/offer/offer.routes";
import orderRoutes from "../modules/order/order.routes";
import additionalInfoRoutes from "../modules/products/additionalInfo/additionalinfo.routes";
import productsRoutes from "../modules/products/products.routes";
import variantRoutes from "../modules/products/variant/variant.routes";
import reviewRoutes from "../modules/reviews/review.routes";
import smtpRoutes from "../modules/smtp/smtp.routes";
import subCategoriesRoutes from "../modules/subCategory/subCategory.routes";
import userRoutes from "../modules/user/user.routes";
import verificationRoutes from "../modules/verification/verification.routes";
import wishlistRoute from "../modules/wishlist/wishlist.routes";
const router = Router();
router.use("/auth", authRouter);
router.use("/users", userRoutes);
router.use("/smtp", smtpRoutes);
router.use("/email-templates", emailTemplateRoutes);
router.use("/verify", verificationRoutes);
router.use("/categories", categoriesRoutes);
router.use("/sub-categories", subCategoriesRoutes);
router.use("/child-categories", childCategoriesRoutes);
router.use("/address", addressRoutes);
router.use("/products", productsRoutes);
router.use("/variants", variantRoutes);
router.use("/additional-info", additionalInfoRoutes);
router.use("/offers", offersRoute);
router.use("/coupons", couponRoute);
router.use("/wishlist", wishlistRoute);
router.use("/cart", cartRoute);
router.use("/orders", orderRoutes);
router.use("/reviews", reviewRoutes);
// router.use("/offer-on-product", offerOnProductRoute);

export default router;
